# Generated by Django 5.1.7 on 2025-04-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("price", models.TextField()),
                ("description", models.TextField()),
                ("color", models.TextField()),
                ("manufacturerName", models.TextField()),
                ("imgRef", models.TextField()),
                ("characteristics", models.JSONField()),
            ],
        ),
    ]
