# Generated by Django 5.1.7 on 2025-04-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.TimeField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "formed"),
                            (2, "built"),
                            (3, "delivered"),
                            (4, "received"),
                        ]
                    ),
                ),
                ("cost", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PickUpPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("address", models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name="product",
            old_name="imgRef",
            new_name="img_ref",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="manufacturerName",
            new_name="manufacturer",
        ),
    ]
