# Generated by Django 5.1.7 on 2025-04-05 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_user_order_pickup_point_alter_order_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pickuppoint",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pickuppoint",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="characteristics",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default="", max_length=3000),
        ),
        migrations.AlterField(
            model_name="product",
            name="img_ref",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="manufacturer",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
