# Generated by Django 5.1.7 on 2025-04-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_order_timestamp_order_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
    ]
