# Generated by Django 5.1.7 on 2025-05-06 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_order_cost_alter_cart_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="main.user",
            ),
            preserve_default=False,
        ),
    ]
