# Generated by Django 5.1.7 on 2025-05-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
