# Generated by Django 5.1.7 on 2025-05-06 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_manufacturer_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="pickuppoint",
            name="address",
            field=models.CharField(max_length=1000, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="pickuppoint",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата добавления"
            ),
        ),
        migrations.AlterField(
            model_name="pickuppoint",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="main.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="characteristics",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Характеристики"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(max_length=30, verbose_name="Цвет"),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата добавления"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, default="", max_length=3000, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="img_ref",
            field=models.URLField(verbose_name="Ссылка на изображение"),
        ),
        migrations.AlterField(
            model_name="product",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="main.manufacturer",
                verbose_name="Производитель",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
    ]
