# Generated by Django 5.1.7 on 2025-05-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_category_name_alter_manufacturer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firstname",
            field=models.CharField(default="", max_length=64, verbose_name="Имя"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="login",
            field=models.CharField(
                default="", max_length=64, unique=True, verbose_name="Логин"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="patronymic",
            field=models.CharField(default="", max_length=64, verbose_name="Отчество"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(default="", max_length=64, verbose_name="Фамилия"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Эл. почта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="Пароль"),
        ),
    ]
