name: frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ] 
    paths:
      - 'frontend/**'

jobs:      
  deploy:
    name: deploy
    runs-on: self-hosted  
    steps:
      - name: Deploy with Docker Compose
        run: |
          cd /home/superfrog/ft/vuz/tkr/repo
          cd frontend
          docker-compose down
          docker-compose up -d --build
